---
title: "08 Interperobility - SCANPY"
output: html_document
---

Interact scanpy with NICHES using PBMC 3k

# Pkg prep

```{r}
# install NICHES
#devtools::install()
library(NICHES)

# Load ALRA
devtools::source_url('https://raw.githubusercontent.com/KlugerLab/ALRA/master/alra.R')

# Set up reticulate and the python env
#install.packages("reticulate")
Sys.setenv(RETICULATE_PYTHON = "/Users/jessie/anaconda3/bin/python")
library(reticulate)
```


```{python}
import numpy as np
import matplotlib.pyplot as plt
import scanpy as sc
```

```{python Figure settings}
sc.set_figure_params(dpi=300,figsize=(20,16))
```

# Load the data and preprocess

```{python}
# load the raw pbmc3k and the processed pbmc3k
adata = sc.datasets.pbmc3k()
adata2 = sc.datasets.pbmc3k_processed()
```

```{python Data Processing}
# Filtering
sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_genes(adata, min_cells=3)
adata.var['mt'] = adata.var_names.str.startswith('MT-')
sc.pp.calculate_qc_metrics(adata, qc_vars=['mt'], percent_top=None, log1p=False, inplace=True)
adata = adata[adata.obs.n_genes_by_counts < 2500, :]
adata = adata[adata.obs.pct_counts_mt < 5, :]
# Log1p normalization
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)
# Assign labels
adata.obs['louvain'] = adata2.obs['louvain']
```

# Visualize the data
```{python}
with plt.rc_context({"figure.figsize": (8, 8), "figure.dpi": (300)}):
    sc.pl.umap(adata2, color='louvain',legend_loc ="on data")
```

# Subset to only 'B cells','CD4 T cells','CD14+ Monocytes'

```{python}
adata = adata[adata.obs['louvain'].isin(['B cells','CD4 T cells','CD14+ Monocytes']),:]

cell_names = np.array(adata.obs_names)
gene_names = np.array(adata.var_names)
```


# Extract the meta data and impute the data to run NICHES
```{r Prep and Imputation}
meta.data.df <- data.frame("louvain" = py$adata$obs$louvain,row.names = py$cell_names)

# alra imputation
imputed.list <- alra(as.matrix(py$adata$X))
data.imputed <- t(imputed.list[[3]])

#potential bug: colnames and rownames of the matrix have to be set
colnames(data.imputed) <- py$cell_names
rownames(data.imputed) <- py$gene_names
```

# Run NICHES

```{r}
niches_list <- RunNICHES(data.imputed,
                 meta.data.df = meta.data.df,
                 cell_types = "louvain",
                 species = 'human',
                 LR.database = 'fantom5',
                 CellToCell = T,output_format = "raw"
                 )
lr_names <- rownames(niches_list$CellToCell$CellToCellMatrix)
```

# convert the output to AnnData

```{python}
adata_niches = sc.AnnData(X = r.niches_list['CellToCell']['CellToCellMatrix'].T)
adata_niches.obs = r.niches_list['CellToCell']['metadata']
adata_niches.var_names = r.lr_names
```

# Process the output from NICHES using scanpy

```{python}
# data scaling, pca, find neighbors, and umap
sc.pp.scale(adata_niches)
sc.tl.pca(adata_niches)
sc.pp.neighbors(adata_niches)
sc.tl.umap(adata_niches)
```


# Visualize CellToCell matrix

```{python}
with plt.rc_context({"figure.figsize": (8, 8), "figure.dpi": (300)}):
    sc.pl.umap(adata_niches,color="VectorType",legend_loc ="on data",legend_fontsize=7)
```

# Differential LR analysis

```{python}
sc.tl.rank_genes_groups(adata_niches, 'VectorType', method='logreg', solver='liblinear',penalty='l1')
with plt.rc_context({"figure.figsize": (8, 12), "figure.dpi": (300)}):
    sc.pl.rank_genes_groups(adata_niches, n_genes=5, sharey=False,show=True,fontsize=20)
```

```{python}
marker_LRs = np.array([g for g in adata_niches.uns['rank_genes_groups']['names'][0]])
```



```{python}
# check specific LRs
with plt.rc_context({"figure.figsize": (10,7), "figure.dpi": (300),"font.size":(8)}):
    sc.pl.violin(adata_niches, marker_LRs[0], groupby='VectorType',rotation=20)
```

```{python}
with plt.rc_context({"figure.figsize": (8, 8), "figure.dpi": (300)}):
    sc.pl.umap(adata_niches, color=marker_LRs[:2],ncols=2)
```


```{python}
with plt.rc_context({"figure.dpi": (300),"font.size":(10)}):
    sc.pl.dotplot(adata_niches, marker_LRs, groupby='VectorType',figsize=(20,10))
```


