---
title: "Simulation case 1: Hidden intra-cluster heterogeneity"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(NICHES)
library(Seurat)
library(ggplot2)
library(ggpubr)
```

In this simulation example, we designed 2 cell populations where each has hidden subpopulations communicating in distinct ways not captured in gene space.

```{r cars}
## Simulation 

# for each subpopulation, the number of cells
n_cell_sub <- 100
n_markers <- 50
n_noise <- 5000
set.seed(34)

l1 <- c(rnbinom(n = n_cell_sub,mu=1,size=20),rnbinom(n = n_cell_sub,mu=30,size=20),
        rep(0,n_cell_sub*2))
r1 <- c(rep(0,n_cell_sub*2),rnbinom(n = n_cell_sub,mu=30,size=20),rnbinom(n = n_cell_sub,mu=30,size=20))

l2 <- c(rnbinom(n = n_cell_sub,mu=30,size=20),rnbinom(n = n_cell_sub,mu=30,size=20),rep(0,n_cell_sub*2))
r2 <-  c(rep(0,n_cell_sub*2),rnbinom(n = n_cell_sub,mu=30,size=20),rnbinom(n = n_cell_sub,mu=1,size=20))

markers <- cbind(matrix(rnbinom(n = n_cell_sub*2*n_markers,mu=10,size=20),nrow = n_markers,ncol = n_cell_sub*2),
                 matrix(rnbinom(n = n_cell_sub*2*n_markers,mu=20,size=20),nrow = n_markers,ncol = n_cell_sub*2))
noise <- matrix(rnbinom(n = n_cell_sub*4*n_noise,mu=15,size=20),nrow = n_noise,ncol = n_cell_sub*4)

input_mat <- rbind(l1,r1,l2,r2,markers,noise)

rownames(input_mat) <- c("A2m","Lrp1","Ace","Agtr2",paste0("G",1:n_markers),paste0("N",1:n_noise))
colnames(input_mat) <- paste0("Cell",1:(n_cell_sub*4))
```


```{r pressure, echo=FALSE}
####################
## Preprocessing ##
####################
# Construct the seurat input
cell_type_annotations <- as.data.frame(c(rep("C1",n_cell_sub*2),rep("C2",n_cell_sub*2)))
rownames(cell_type_annotations) <- colnames(input_mat)
cell_type_annotations$cell_type_sub <- paste0("S",c(rep(1,n_cell_sub),rep(2,n_cell_sub),rep(3,n_cell_sub),rep(4,n_cell_sub)))
colnames(cell_type_annotations) <- c("cell_types_main","cell_types_sub")
seu_obj_sim1 <- Seurat::CreateSeuratObject(counts = input_mat,meta.data=cell_type_annotations)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
# Some further preprocessing 
Seurat::Idents(seu_obj_sim1) <- "cell_types_main"
# Normalize the data: scaled by the cell size
seu_obj_sim1 <- Seurat::NormalizeData(seu_obj_sim1)
seu_obj_sim1 <- Seurat::FindVariableFeatures(seu_obj_sim1,selection.method="disp")
seu_obj_sim1 <- Seurat::ScaleData(seu_obj_sim1)
seu_obj_sim1 <- Seurat::RunPCA(seu_obj_sim1,npcs =50)
seu_obj_sim1 <- Seurat::RunTSNE(seu_obj_sim1,dims=1:30)
```

```{r}
Seurat::DimPlot(seu_obj_sim1,reduction = "tsne",group.by = "cell_types_main",pt.size = 1.5)+ggtitle("")
```

```{r}
Seurat::DimPlot(seu_obj_sim1,reduction = "tsne",group.by = "cell_types_sub",pt.size = 1.5)+ggtitle("")
```

```{r}
p_vln <- Seurat::VlnPlot(seu_obj_sim1,features =  c("A2m","Lrp1","Ace","Agtr2"),group.by = "cell_types_sub",slot = "data",ncol = 2,combine = FALSE,pt.size = 0.3)
ggpubr::ggarrange(p_vln[[1]]+NoLegend()+xlab("")+ggtitle("Ligand 1: A2m"),
             p_vln[[2]]+NoLegend()+xlab("")+ggtitle("Receptor 1: Lrp1"),
             nrow=2)

```

```{r}
ggpubr::ggarrange(
             p_vln[[3]]+NoLegend()+xlab("")+ggtitle("Ligand 2: Ace"),
             p_vln[[4]]+NoLegend()+xlab("")+ggtitle("Receptor 2: Agtr2"),nrow=2)
```

```{r}
#############
## RunNICHES ##
#############

sim1 <- NICHES::RunNICHES(object = seu_obj_sim1,LR.database = "fantom5",species = "mouse",assay = "RNA",
                        meta.data.to.map = c('cell_types_main','cell_types_sub','nCount_RNA'),
                        CellToCell = T,CellToSystem = F,SystemToCell = F,
                        CellToCellSpatial =F,CellToNeighborhood = F,NeighborhoodToCell =F)
```

```{r}
# only take the vector types C1 -> C2
sim1_sub <- subset(sim1[['CellToCell']],idents = "C1-C2")

data_mat_df <- as.data.frame(t(as.matrix(sim1_sub@assays$CellToCell@data)))
data_mat_df$vector_types <- sim1_sub@meta.data$VectorType
data_mat_df$vector_types_sub <- sim1_sub@meta.data$cell_types_sub.Joint

colnames(data_mat_df) <- c("A2m_Lrp1","Ace_Agtr2","vector_types","vector_types_sub")
```


```{r}
# k-means clustering
k4 <- kmeans(data_mat_df[,1:2],centers = 4)
data_mat_df$cluster_label <- as.character(k4$cluster)

p_clustering <- ggplot(data_mat_df, aes(x=A2m_Lrp1, y=Ace_Agtr2,  color=cluster_label)) +
  geom_point(size=4)+
  scale_color_manual(values=c("#56B4E9","salmon", "#E69F00","green4"))+
  ggtitle("Clustering of the cell-cell vectors") + theme_classic()
p_clustering_adj <- p_clustering +theme(legend.background = element_rect(color = NA),
                                        legend.position = "bottom",
                                        axis.text=element_text(color="black",size=25),
                                        axis.title = element_text(color="black",size=25),
                                        legend.text = element_text(color="black",size=25),
                                        legend.title = element_text(color="black",size=25)) + ggtitle("")

```

```{r}
p_clustering_adj
```

```{r}
# calculate cellphonedb edge-weights
A2m_mean <- mean(seu_obj_sim1@assays$RNA@data['A2m',seu_obj_sim1@meta.data$cell_types_main == "C1"])
Lrp1_mean <- mean(seu_obj_sim1@assays$RNA@data['Lrp1',seu_obj_sim1@meta.data$cell_types_main == "C2"])
A2m_Lrp1_prod <- A2m_mean*Lrp1_mean

Ace_mean <- mean(seu_obj_sim1@assays$RNA@data['Ace',seu_obj_sim1@meta.data$cell_types_main == "C1"])
Agtr2_mean <- mean(seu_obj_sim1@assays$RNA@data['Agtr2',seu_obj_sim1@meta.data$cell_types_main == "C2"])
Ace_Agtr2_prod <- Ace_mean*Agtr2_mean

cellphdb_df <- as.data.frame(A2m_Lrp1_prod)
rownames(cellphdb_df) <- "all_cells"
colnames(cellphdb_df) <- "A2m_Lrp1"
cellphdb_df$Ace_Agtr2 <- Ace_Agtr2_prod
cellphdb_df$vector_types <- "C1-C2"
cellphdb_df$vector_types_sub <- "C1-C2"
cellphdb_df$cluster_label <- "none"

data_mat_df2 <- rbind(data_mat_df,cellphdb_df)

data_mat_df2$true_label <- c(paste0(data_mat_df$vector_types_sub),"C1 - C2") 

p_label <- ggplot(data_mat_df2, aes(x=A2m_Lrp1, y=Ace_Agtr2,  color=true_label)) +
  geom_point(size=4)+
  scale_color_manual(values=c("black", "#E69F00","#56B4E9","salmon","green4"))+
  ggtitle("Ground truth interaction profiles")
p_label_adj <- p_label + theme_classic() +theme(legend.background = element_rect(color = NA),
                                                legend.position = "bottom",
                                                axis.text=element_text(color="black",size=25),
                                                axis.title = element_text(color="black",size=25),
                                                legend.text = element_text(color="black",size=25),
                                                legend.title = element_text(color="black",size=25),
                                                ) + ggtitle("")

```


```{r}
p_label_adj
```

