---
title: "Simulation case 2: Differential signaling distributions in disparate experimental conditions"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(NICHES)
library(Seurat)
library(ggplot2)
library(ggpubr)
library(cowplot)
```


```{r cars}
# Specify number of cells, marker genes, noisy genes 
n_cell_per_type <- 100
n_marker_genes <- 50
n_noise_genes <- 5000
set.seed(34)
```


```{r pressure, echo=FALSE}
############
## Case 1 ##
############
#  Only 10 cells of Cell_type 1 (c1) highly express ligand 1 (l1)
#  Other cells (90 cells of c1 and 100 cells of c2) don't express l1
mean_expression_l1_c1_high <- 100
l1 <- c(rnbinom(n = 10, mu = mean_expression_l1_c1_high,size=20),rep(0,90),rep(0,n_cell_per_type))
print(paste0("Ligand 1's mean expression level of Cell type 1: ",mean(l1[1:n_cell_per_type])))
# Only cells of c2 express recetpr 1 (r1)
mean_expression_r1_c2 <- 5
r1 <- c(rep(0,n_cell_per_type),rnbinom(n = n_cell_per_type, mu = mean_expression_r1_c2,size=20))
print(paste0("Receptor 1's mean expression level of Cell type 2: ",mean(r1[(n_cell_per_type+1):length(r1)])))
# Marker genes to distinguish c1 from c2
marker_c1_mean <- 10
marker_c2_mean <- 20
markers <- cbind(matrix(rnbinom(n = n_cell_per_type*n_marker_genes,mu=marker_c1_mean,size=20),nrow = n_marker_genes,ncol = n_cell_per_type),
                 matrix(rnbinom(n = n_cell_per_type*n_marker_genes,mu=marker_c2_mean,size=20),nrow = n_marker_genes,ncol = n_cell_per_type))
# Noise genes
noise_mean <- 15
noise <- matrix(rnbinom(n = n_cell_per_type*2*n_noise_genes,mu=noise_mean,size=20),nrow = n_noise_genes,ncol = n_cell_per_type*2)
# Combining them
count_matrix1 <- rbind(l1,r1,markers,noise)
nrow(count_matrix1)
ncol(count_matrix1)
rownames(count_matrix1) <- c("A2m","Lrp1",paste0("G",1:n_marker_genes),paste0("N",1:n_noise_genes))
colnames(count_matrix1) <- paste0("Cell",1:(n_cell_per_type*2))
# Preprocessing
# Construct the seurat input
cell_type_annotations <- as.data.frame(c(rep("C1",n_cell_per_type),rep("C2",n_cell_per_type)))
rownames(cell_type_annotations) <- colnames(count_matrix1)
colnames(cell_type_annotations) <- c("cell_types")
seu_obj_sim1 <- Seurat::CreateSeuratObject(counts = count_matrix1,meta.data=cell_type_annotations)
Seurat::Idents(seu_obj_sim1) <- "cell_types"
seu_obj_sim1 <- Seurat::NormalizeData(seu_obj_sim1)
seu_obj_sim1 <- Seurat::FindVariableFeatures(seu_obj_sim1,selection.method="disp")
seu_obj_sim1 <- Seurat::ScaleData(seu_obj_sim1)
seu_obj_sim1 <- Seurat::RunPCA(seu_obj_sim1,npcs = 30)
seu_obj_sim1 <- Seurat::RunTSNE(seu_obj_sim1,dims= 1:30,seed.use = 34)
```


```{r}
Seurat::DimPlot(seu_obj_sim1,reduction = "tsne",group.by = "cell_types")
```

```{r}
SCC_sim1 <- NICHES::RunNICHES(object = seu_obj_sim1,LR.database = "fantom5",species = "mouse",assay = "RNA",
                        meta.data.to.map = c('cell_types','orig.ident'), min.cells.per.ident = 0,
                        min.cells.per.gene = 0,
                        CellToCell = T,CellToSystem = F,SystemToCell = F,
                        CellToCellSpatial =F,CellToNeighborhood = F,NeighborhoodToCell =F)

Seurat::Idents(SCC_sim1[[1]]) <- SCC_sim1[[1]]@meta.data$VectorType
SCC_sim1_sub <- subset(SCC_sim1[[1]],idents = "C1—C2")
SCC_sim1_sub@meta.data$case <- "1"

```

```{r}
############
## Case 2 ##
############
#  all the cells of Cell_type 1 (c1) express ligand 1 (l1)
#  c2 don't express l1
mean_expression_l1_c1 <- 10
l1 <- c(rnbinom(n = n_cell_per_type, mu = mean_expression_l1_c1,size=20),rep(0,n_cell_per_type))
print(paste0("Ligand 1's mean expression level of Cell type 1: ",mean(l1[1:n_cell_per_type])))
# Other settings (r1,markers,noise) remain the same as in case 1
count_matrix2 <- rbind(l1,r1,markers,noise)
nrow(count_matrix2)
ncol(count_matrix2)
rownames(count_matrix2) <- c("A2m","Lrp1",paste0("G",1:n_marker_genes),paste0("N",1:n_noise_genes))
colnames(count_matrix2) <- paste0("Cell",1:(n_cell_per_type*2))
# Preprocessing
# Construct the seurat input
cell_type_annotations <- as.data.frame(c(rep("C1",n_cell_per_type),rep("C2",n_cell_per_type)))
rownames(cell_type_annotations) <- colnames(count_matrix2)
colnames(cell_type_annotations) <- c("cell_types")
seu_obj_sim2 <- Seurat::CreateSeuratObject(counts = count_matrix2,meta.data=cell_type_annotations)
Seurat::Idents(seu_obj_sim2) <- "cell_types"
seu_obj_sim2 <- Seurat::NormalizeData(seu_obj_sim2)
seu_obj_sim2 <- Seurat::FindVariableFeatures(seu_obj_sim2,selection.method="disp")
seu_obj_sim2 <- Seurat::ScaleData(seu_obj_sim2)
seu_obj_sim2 <- Seurat::RunPCA(seu_obj_sim2,npcs = 30)
seu_obj_sim2 <- Seurat::RunTSNE(seu_obj_sim2,dims= 1:30,seed.use = 34)
```

```{r}
Seurat::DimPlot(seu_obj_sim2,reduction = "tsne",group.by = "cell_types")
```

```{r}
SCC_sim2 <- NICHES::RunNICHES(object = seu_obj_sim2,LR.database = "fantom5",species = "mouse",assay = "RNA",
                        meta.data.to.map = c('cell_types','orig.ident'),min.cells.per.ident = 0,
                        min.cells.per.gene = 0,
                        CellToCell = T,CellToSystem = F,SystemToCell = F,
                        CellToCellSpatial =F,CellToNeighborhood = F,NeighborhoodToCell =F)

Seurat::Idents(SCC_sim2[[1]]) <- SCC_sim2[[1]]@meta.data$VectorType
SCC_sim2_sub <- subset(SCC_sim2[[1]],idents = "C1—C2")
SCC_sim2_sub@meta.data$case <- "2"
```

```{r}
# Testing
SCC_combo <- merge(SCC_sim1_sub,SCC_sim2_sub)
Seurat::Idents(SCC_combo) <- SCC_combo@meta.data$case

wilcox.test(x=SCC_combo@assays$CellToCell@data[1,Seurat::Idents(SCC_combo)=="1"],
            y=SCC_combo@assays$CellToCell@data[1,Seurat::Idents(SCC_combo)=="2"])
```

```{r, echo=FALSE}
#Plotting MSBR
p1 <- Seurat::DimPlot(seu_obj_sim1,reduction = "tsne",group.by = "cell_types")+ggtitle('Case1')
p2 <- FeaturePlot(seu_obj_sim1,'A2m')
p3 <- FeaturePlot(seu_obj_sim1,'Lrp1')
p4 <- Seurat::DimPlot(seu_obj_sim2,reduction = "tsne",group.by = "cell_types")+ggtitle('Case2')
p5 <- FeaturePlot(seu_obj_sim2,'A2m')
p6 <- FeaturePlot(seu_obj_sim2,'Lrp1')

temp <- ggpubr::ggarrange(p1,p2,p3,p4,p5,p6,nrow = 2)

```




```{r}
# Compare mean values and plot
avg.exp.1 <- data.frame(AverageExpression(seu_obj_sim1))
avg.exp.2 <- data.frame(AverageExpression(seu_obj_sim2))
avg.exp.1$gene <- rownames(avg.exp.1)
avg.exp.2$gene <- rownames(avg.exp.2)
avg.exp.1 <- avg.exp.1[c('A2m','Lrp1'),]
avg.exp.2 <- avg.exp.2[c('A2m','Lrp1'),]
avg.exp.1$case <- 'Case1'
avg.exp.2$case <- 'Case2'
avg.exp <- rbind(avg.exp.1,avg.exp.2)

p7 <- ggplot(avg.exp,aes(x=case,y=RNA.C1,color = case,fill=case)) +
  geom_bar(stat = 'identity')+
  ggtitle('Mean Connectivity')+
  ylab('Mean Connectivity')+
  ylim(0,1.25*max(avg.exp$RNA.C1))+ stat_compare_means(label.x = 1.4,label.y = 1.6)+theme_classic()
p8 <- VlnPlot(SCC_combo,'A2m—Lrp1')+ylim(0,1.1*max(SCC_combo@assays$CellToCell@data))+ 
  stat_compare_means(label.x = 1.3,label.y = 3)+
  ggtitle('NICHES Output')+xlab(NULL)+theme_classic()
temp2 <- plot_grid(p7,p8)
```

```{r}
ggpubr::ggarrange(temp2,nrow=1)
```

