---
title: "Simulation case 3"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(NICHES)
library(Seurat)
library(ggplot2)
library(ggpubr)
```


```{r cars}
# Specify number of cells, marker genes, noisy genes 
n_cell_per_type <- 1000
n_marker_genes <- 50
n_noise_genes <- 5000
set.seed(34)
```


```{r pressure, echo=FALSE}
# 3 cell types: c1, c2, c3
# c3's ligand expression levels is similar to c1
# but with different marker expression levels
mean_expression_l1_c1 <- 5
mean_expression_l2_c1 <- 5
mean_expression_r1_c2 <- 30
mean_expression_r2_c2 <- 30
l1 <- c(rnbinom(n = n_cell_per_type, mu = mean_expression_l1_c1,size=20),rep(0,n_cell_per_type),rnbinom(n = n_cell_per_type, mu = mean_expression_l1_c1,size=20))
r1 <- c(rep(0,n_cell_per_type),rnbinom(n = n_cell_per_type, mu = mean_expression_r1_c2,size=20),rep(0,n_cell_per_type))
l2 <- c(rnbinom(n = n_cell_per_type, mu = mean_expression_l2_c1,size=20),rep(0,n_cell_per_type),rnbinom(n = n_cell_per_type, mu = mean_expression_l2_c1,size=20))
r2 <- c(rep(0,n_cell_per_type),rnbinom(n = n_cell_per_type, mu = mean_expression_r2_c2,size=20),rep(0,n_cell_per_type))
```

```{r}
# Marker genes to distinguish c1,c2,c3
marker_c1_mean <- 10
marker_c2_mean <- 20
marker_c3_mean <- 30
markers <- cbind(matrix(rnbinom(n = n_cell_per_type*n_marker_genes,mu=marker_c1_mean,size=20),nrow = n_marker_genes,ncol = n_cell_per_type),
                 matrix(rnbinom(n = n_cell_per_type*n_marker_genes,mu=marker_c2_mean,size=20),nrow = n_marker_genes,ncol = n_cell_per_type),
                 matrix(rnbinom(n = n_cell_per_type*n_marker_genes,mu=marker_c3_mean,size=20),nrow = n_marker_genes,ncol = n_cell_per_type))
# Noise genes
noise_mean <- 15
noise <- matrix(rnbinom(n = n_cell_per_type*3*n_noise_genes,mu=noise_mean,size=20),nrow = n_noise_genes,ncol = n_cell_per_type*3)
# Combining them
count_matrix2 <- rbind(l1,r1,l2,r2,markers,noise)
nrow(count_matrix2)
ncol(count_matrix2)
rownames(count_matrix2) <- c("A2m","Lrp1","Ace","Agtr2",paste0("G",1:n_marker_genes),paste0("N",1:n_noise_genes))
colnames(count_matrix2) <- paste0("Cell",1:(n_cell_per_type*3))
```

```{r}
# Preprocessing
# Construct the seurat input
cell_type_annotations <- as.data.frame(c(rep("C1",n_cell_per_type),rep("C2",n_cell_per_type),rep("C3",n_cell_per_type)))
rownames(cell_type_annotations) <- colnames(count_matrix2)
colnames(cell_type_annotations) <- c("cell_types")
seu_obj_sim2 <- Seurat::CreateSeuratObject(counts = count_matrix2,meta.data=cell_type_annotations)
Seurat::Idents(seu_obj_sim2) <- "cell_types"
seu_obj_sim2 <- Seurat::NormalizeData(seu_obj_sim2)
seu_obj_sim2 <- Seurat::FindVariableFeatures(seu_obj_sim2,selection.method="disp")
seu_obj_sim2 <- Seurat::ScaleData(seu_obj_sim2)
seu_obj_sim2 <- Seurat::RunPCA(seu_obj_sim2,npcs = 30)
seu_obj_sim2 <- Seurat::RunTSNE(seu_obj_sim2,dims= 1:30,seed.use = 34)
```

```{r}
Seurat::DimPlot(seu_obj_sim2,reduction = "tsne",group.by = "cell_types")
```

```{r}
####################################
## Case 1: only c1 and c2 for NICHES ##
####################################
# Run NICHES
sim1 <- NICHES::RunNICHES(object = subset(seu_obj_sim2,idents = c("C1","C2")),LR.database = "fantom5",species = "mouse",assay = "RNA",meta.data.to.map = c('cell_types','orig.ident'),
                        CellToCell = F,CellToSystem = F,SystemToCell = T,
                        CellToCellSpatial =F,CellToNeighborhood = F,NeighborhoodToCell =F,blend = 'sum')

```

```{r}
# only take the receiving type == c2
#Seurat::Idents(sim1[['SystemToCell']])
sim1_sub <- subset(sim1[['SystemToCell']],idents = "C2")
data_mat_df <- as.data.frame(t(as.matrix(sim1_sub@assays$SystemToCell@data)))
data_mat_df$ReceivingType <- sim1_sub@meta.data$ReceivingType
colnames(data_mat_df) <- c("A2m_Lrp1","Ace_Agtr2","ReceivingType")
```


```{r}
#######################################
## Case 2: c1, c2, c3 all for NICHES ##
#######################################
# Run NICHES
sim2 <- NICHES::RunNICHES(object = seu_obj_sim2,LR.database = "fantom5",species = "mouse",assay = "RNA",
                        meta.data.to.map = c('cell_types','orig.ident'),
                        CellToCell = F,CellToSystem = F,SystemToCell = T,
                        CellToCellSpatial =F,CellToNeighborhood = F,NeighborhoodToCell =F,blend = 'sum')
```

```{r}
# only take the receiving type == c2
sim2_sub <- subset(sim2[['SystemToCell']],idents = "C2")
data_mat_df2<- as.data.frame(t(as.matrix(sim2_sub@assays$SystemToCell@data)))
data_mat_df2$ReceivingType <- sim2_sub@meta.data$ReceivingType
colnames(data_mat_df2) <- c("A2m_Lrp1","Ace_Agtr2","ReceivingType")
```



```{r}
# stack both
data_mat_df$case <- "1"
data_mat_df2$case <- "2"
data_mat_df_combo <- rbind(data_mat_df,data_mat_df2)

ggplot(data_mat_df_combo, aes(x=A2m_Lrp1, y=Ace_Agtr2,  color=case)) +
  geom_point()
```

