---
title: "Using NICHES with Spatial Datasets"
author: "Micha Sam Brickman Raredon & Junchen Yang"
date: "`r Sys.Date()`"
vignette: |
  %\VignetteIndexEntry{Using NICHES with Spatial Datasets} %\VignetteEngine{knitr::rmarkdown} %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Load Dependencies
```{r message=F}
library(Seurat)
library(SeuratData)
library(SeuratWrappers)
library(ggplot2)
library(patchwork)
library(dplyr)
library(cowplot)
library(viridis)
```


```{r}
source("./spatial_vignette_preprocess.R")
cortex <- spatial_vignette_preprocessing()
```


```{r}
cell_type_colors <- c("darkorchid2","green4","mediumspringgreen","#8DA0CB",
                        "orangered3","dodgerblue4","burlywood3","darkblue",
                        "cyan2" , "maroon4")
names(cell_type_colors) <- levels(cortex@meta.data$cell_type)
fig_D1 <- SpatialDimPlot(cortex, crop = TRUE, label = F,pt.size.factor = 2.2,cols = cell_type_colors)+NoLegend()
fig_D2 <- get_legend(SpatialDimPlot(cortex, crop = TRUE, label = F,pt.size.factor = 10,cols = cell_type_colors)
                        +guides(fill = guide_legend(title="Cell types",ncol = 1,override.aes = list(size = 4))))
fig_D1 
plot_grid(fig_D2)
```

```{r}
# Impute the data with ALRA
DefaultAssay(cortex) <- "Spatial"
cortex <- NormalizeData(cortex)
cortex <- RunALRA(cortex,setDefaultAssay = TRUE)

cortex@meta.data$x <- cortex@images$anterior1@coordinates$row
cortex@meta.data$y <- cortex@images$anterior1@coordinates$col
```

```{r}
library(NICHES)

cortex@assays$alra@counts <- cortex@assays$Spatial@counts
NICHES.list <- RunNICHES(object = cortex,LR.database = "fantom5",species = "mouse",assay = "alra",
                       position.x = 'x', 
                       position.y = 'y',
                       rad.set = 2, 
                       k = NULL,
                       min.cells.per.ident = 0, 
                       meta.data.to.map = c('orig.ident','cell_type'),
                       CellToCell = F,CellToSystem = F,SystemToCell = F,
                       CellToCellSpatial = T,CellToNeighborhood = F,NeighborhoodToCell = T)
```


```{r}
niche <- NICHES.list[['NeighborhoodToCell']]
Idents(niche) <- niche[['ReceivingType']]
#Limit analysis to populations > 50 measurements
POI_niche <- names(table(Idents(niche))[table(Idents(niche))>50])
niche <- subset(niche,idents = POI_niche)
# Scale and visualize
niche <- ScaleData(niche)
niche <- FindVariableFeatures(niche,selection.method = "disp")
niche <- RunPCA(niche)
niche <- RunUMAP(niche,dims = 1:30)
cell_type_colors_sub <- cell_type_colors[as.character(unique(Idents(niche)))]
DimPlot(niche,reduction = 'umap',pt.size = 0.5,shuffle = T,cols = cell_type_colors_sub) +ggtitle('Niche Matrix Embedding from ST data')
```

```{r}
# Find markers
mark <- FindAllMarkers(niche,min.pct = 0.25,only.pos = T,test.use = "roc")
#mark$ratio <- mark$pct.1/mark$pct.2
GOI_niche <- mark %>% group_by(cluster) %>% top_n(10,myAUC)

niche@meta.data$POI_receiving_type <- factor(niche@meta.data$ReceivingType,levels = POI_niche)
Idents(niche) <- niche@meta.data$POI_receiving_type
DoHeatmap(niche,features = unique(GOI_niche$gene),group.by = "POI_receiving_type",group.colors = cell_type_colors_sub) + scale_fill_gradientn(colors = c("grey","white", "blue"))
```

```{r}
SpatialFeaturePlot(cortex, crop = TRUE, features = "Fgf1",slot = "data",min.cutoff =  'q1',
                         max.cutoff = 'q99')+ggtitle("Ligand")+theme(legend.position = "right")
SpatialFeaturePlot(cortex, crop = TRUE, features = "Fgfr2",slot = "data",min.cutoff =  'q1',
                         max.cutoff = 'q99')+ggtitle("Receptor")+theme(legend.position = "right")
```

```{r}
sessionInfo()
```

